config/routes.rb
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  get 'settings/purge' => 'settings#purge', :as => :purge
  root "url_entries#index"
  get 'search/' => 'url_entries#search', :as => :search
  get 'visit/:id' => 'url_entries#visit', :as => :visit

  resources :settings
  resources :url_entries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/setting.rb
class Setting < ApplicationRecord

    def filter_chars_array
        self.filter_chars.split(" ")
    end
end

app/models/url_entry.rb
class UrlEntry < ApplicationRecord

    scope :active, -> { where(archived: false) }
    scope :sponsored_first, -> { where(sponsored:true).or(where(sponsored:false)).order(sponsored: :desc)}


    def increment
        new_count = self.counter + 1
        self.update(counter: new_count)
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def is_admin?
    self.level == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def is_admin
        unless current_user && current_user.is_admin?
            redirect_to controller: 'url_entries', action: 'index', notice: "forbidden"
            # redirect_to :index, flash: {errors: "Forbidden"}
        end

    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[ show edit update destroy ]
  before_action :is_admin
  @setting
  @settings

  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  # def destroy
  #   @setting.destroy

  #   respond_to do |format|
  #     format.html { redirect_to settings_url, notice: "Setting was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  def purge
    UrlEntry.active.where("expire < ?", DateTime.now).update(archived: true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.require(:setting).permit(:filter_chars)
    end
end

app/controllers/url_entries_controller.rb
class UrlEntriesController < ApplicationController
  before_action :set_url_entry, only: %i[ show edit update destroy ]
  before_action :is_admin, only: %i[ create edit update destroy ]
  @url_entry
  @url_entries

  # GET /url_entries or /url_entries.json
  def index
    @url_entries = UrlEntry.all.active.sponsored_first
    if(params[:page] == 'all')
      @url_entries = @url_entries.page(1).per(@url_entries.count)
    else
      @url_entries = @url_entries.page(params[:page]).per(3)
    end
  end

  # GET /url_entries/1 or /url_entries/1.json
  def show
  end

  def search
    keywords = settings_filter_chars(params[:query].split(' '))
    query_type = params[:query_type]
    sort_order = params[:sort_order]

    if query_type == 'AND'
      @url_entries = perform_and_search(keywords)
    elsif query_type == 'NOT'
      @url_entries = perform_not_search(keywords)
    else
      @url_entries = perform_or_search(keywords)
    end

    if sort_order == "counter"
      @url_entries = @url_entries.order(counter: :desc)
    end
    if sort_order == "description"
      @url_entries = @url_entries.order(:description)
    end

    @url_entries = @url_entries.active.sponsored_first

    if(params[:page] == 'all')
      @url_entries = @url_entries.page(1).per(@url_entries.count)
    else
      per_page = params[:per_page] || 3
      @url_entries = @url_entries.page(params[:page]).per(per_page)
    end
    
    respond_to do |format|
      format.html { @url_entries}
      format.json { render json: @url_entries }
    end

  end

  def visit
    @url_entry = UrlEntry.find(params[:id])
    @url_entry.increment
    redirect_to(@url_entry.url, allow_other_host: true)
  end

  # GET /url_entries/new
  def new
    @url_entry = UrlEntry.new
  end

  # GET /url_entries/1/edit
  def edit
  end

  # POST /url_entries or /url_entries.json
  def create
    @url_entry = UrlEntry.new(url_entry_params)

    
    respond_to do |format|
      if valid_url?(@url_entry.url) && @url_entry.save
        format.html { redirect_to url_entry_url(@url_entry), notice: "Url entry was successfully created." }
        format.json { render :show, status: :created, location: @url_entry }
      else
        @url_entry.errors.add(:url, message: "Failed to create URL Entry: check URL formatting")

        format.html { render :new, status: :unprocessable_entity}
        format.json { render json: @url_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /url_entries/1 or /url_entries/1.json
  def update
    respond_to do |format|
      if valid_url?(@url_entry.url) && @url_entry.update(url_entry_params)
        format.html { redirect_to url_entry_url(@url_entry), notice: "Url entry was successfully updated." }
        format.json { render :show, status: :ok, location: @url_entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /url_entries/1 or /url_entries/1.json
  def destroy

    @url_entry.update(archived:true)
    respond_to do |format|
      format.html { redirect_to url_entries_url, notice: "Url entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def settings_filter_chars(keywords)
      keywords = keywords.map { |keyword|
        Setting.first.filter_chars_array.each {|char|
          keyword = keyword.delete(char)
        }
        keyword
      }
      keywords = keywords.reject { |key| key.empty? }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_url_entry
      @url_entry = UrlEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_entry_params
      params.require(:url_entry).permit(:url, :description, :expire, :sponsored)
    end

    def valid_url?(url)
      uri = URI.parse(url)
      uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS)
    rescue URI::InvalidURIError
      false
    end

    def perform_or_search(keywords)
      UrlEntry.where('description LIKE ?', "%#{keywords.first}%").tap do |query|
        keywords.drop(1).each do |keyword|
          query.or!(UrlEntry.where('description LIKE ?', "%#{keyword}%"))
        end
      end
    end
  
    def perform_and_search(keywords)
      UrlEntry.where('description LIKE ?', "%#{keywords.first}%").tap do |query|
        keywords.drop(1).each do |keyword|
          query.where!('description LIKE ?', "%#{keyword}%")
        end
      end
    end
  
    def perform_not_search(keywords)
      UrlEntry.where.not('description LIKE ?', "%#{keywords.first}%").tap do |query|
        keywords.drop(1).each do |keyword|
          query.where.not('description LIKE ?', "%#{keyword}%")
        end
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/url_entries_helper.rb
module UrlEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CometCrawler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/css/autoComplete.min.css">
   

  </head>

  <body style="padding:10px;background-color: #222222;color: #ffffff;">
  <div id="topbar" style="background-color:#333333;border-style:solid;border-radius:10px;border-width:2px;padding:25px;border-color:#dddddd;">
  <% if user_signed_in? %> 
  <div> Welcome <%= current_user.email %> </div> 
    <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
  <% else %>
    <div> Test admin credentials: tth150630@utdallas.edu : password123 </div>
    <%= button_to "Sign in", new_user_session_path %> 
  <% end %>  
  </br> 
    <%= link_to "Home", root_path %> |
    <% if user_signed_in? && current_user.is_admin? %> 
    <%= link_to "New url entry", new_url_entry_path %> |
    <%= link_to "Settings", settings_path %> |
    <% end %>
    <a href="https://github.com/tyharg/CS-4376/" target="_blank">  Readme</a> |
    <a href="https://github.com/tyharg/CS-4376/blob/2ab0b974cd5e019239cbc5d3168ddb5ae67b128f/preliminary-plan.pdf" target="_blank"> Preliminary Project Plan </a>
  </div>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/autoComplete.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/autoComplete.min.js"></script>
    <script>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    fetch('/url_entries.json?page=all')
    .then(response => response.json())
    .then(data => {
      const descriptions = data.map(entry => entry.description);
      const autoCompleteJS = new autoComplete({
        placeHolder: "",
        data: {
            src: descriptions,
            cache: true,
        },
        resultItem: {
            highlight: true
        },
        events: {
            input: {
                selection: (event) => {
                    const selection = event.detail.selection.value;
                    autoCompleteJS.input.value = selection;
                }
            }
        }
    });
        })
        .catch(error => {
          console.error('Error:', error);
        });

      
    </script>

  </body>
</html>

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>
  <% if setting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :filter_chars, style: "display: block" %>
    <%= form.text_field :filter_chars %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/_setting.html.erb
<div id="<%= dom_id setting %>">
  <p>
    <strong>Filter chars:</strong>
    <%= setting.filter_chars %>
  </p>

</div>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Show this setting", @setting %> |
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Settings</h1>

<div id="settings">
  <% @settings.each do |setting| %>
    <%= render setting %>
    <p>
      <%= link_to "Update Settings", setting %>
    </p>

    <p>
    <%= link_to "Purge Expired Links", purge_path, :onclick => "return confirm('This will remove all expired links from the index, are you sure?')" %>
  </p>
  <% end %>
</div>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/purge.html.erb
<div>
<p> Purged Expired Links </p>

<p> <%= link_to "Back", settings_path %> </p>

</div>

app/views/settings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @setting %>

<div>
  <%= link_to "Edit this setting", edit_setting_path(@setting) %> |
  <%= link_to "Back to settings", settings_path %>

</div>

app/views/url_entries/_form.html.erb
<%= form_with(model: url_entry) do |form| %>
  <% if url_entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(url_entry.errors.count, "error") %> prohibited this url_entry from being saved:</h2>

      <ul>
        <% url_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :expire, style: "display: block" %>
    <%= form.datetime_field :expire %>
  </div>

  <div>
  <%= form.label :sponsored, "Paid Sponsor", style: "display: block" %>
  <%= form.check_box :sponsored %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/url_entries/_list_entry.html.erb
<div id="url_entries">
  <% @url_entries.each do |url_entry| %>
    <div style="border-style:solid;border-width:3px; border-radius:5px; border-color: #dddddd;margin:10px;"> 
      <%= render url_entry %>
      <p>
        <%= link_to "Show this url entry", url_entry %>
      </p>
    </div>
    
  <% end %>

  
  <%= link_to_previous_page @url_entries, 'Previous Page' %>
  |
  <%= link_to_next_page @url_entries, 'Next Page' %>

  <%= page_entries_info @url_entries, entry_name: 'URL' %>
  

</div>

app/views/url_entries/_search_form.html.erb
<style>
    #query {
        margin: 7px;
        width: 600px;
        height: 40px;
        font-size: 18px;
        font-weight: bold;
    }
</style>
<%= form_with url: "/search", method: :get do |form| %>
    <%= form.label :query, "Search for:" %>
    <%= form.text_field :query, id: "autoComplete", autocomplete: "off", style: "color: #222222", value: params[:query] %>
    </br>
    </br>

    <%= form.label :query_type, "Query Type:" %>
    <%= form.select :query_type, ['OR', 'AND', 'NOT'], selected: params[:query_type]%>
    </br>
    </br>

    <%= form.label :sort_order, "Sort Order:" %>
    <%= form.select :sort_order, options_for_select([['Most Accessed', 'counter'], ['Alphabetical', 'description']], selected: params[:sort_order])%>
    </br>
    </br>

    <%= form.label :per_page, "Items Per Page:" %>
    <%= form.select :per_page, options_for_select([3, 5, 10, 20, 50], selected: params[:per_page])%>
    </br>
    </br>


    <%= form.submit "Search" %>
  <% end %>
  

app/views/url_entries/_url_entry.html.erb
<div id="<%= dom_id url_entry %>" style="padding:5px;">
  <%= url_entry.sponsored ? "SPONSORED" : "" %>

  <p>
    <strong>Url:</strong>
    <%= link_to "#{url_entry.url}", visit_path(url_entry), target: "_blank"%>
  </p>

  <p>
    <strong>Description:</strong>
    <%= url_entry.description %>
  </p>

  <p>
    <strong>Clicks:</strong>
    <%= url_entry.counter %>
  </p>


  <p>
    <strong>Expire:</strong>
    <%= url_entry.expire %>
  </p>

</div>

app/views/url_entries/edit.html.erb
<h1>Editing url entry</h1>

<%= render "form", url_entry: @url_entry %>

<br>

<div>
  <%= link_to "Show this url entry", @url_entry %> |
  <%= link_to "Back to url entries", root_path %>
</div>

app/views/url_entries/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>CometCrawler v1.09 Index</h1>

<%= render 'search_form' %>

<%= render 'list_entry' %>

app/views/url_entries/new.html.erb
<h1>New url entry</h1>

<%= render "form", url_entry: @url_entry %>

<br>

<div>
  <%= link_to "Back to url entries", url_entries_path %>
</div>

app/views/url_entries/search.html.erb
<p style="color: green"><%= notice %></p>

<h1>Search Results</h1>


<%= render 'search_form' %>

<div style="font-size:25px;">
  <%= link_to "Clear", '/' %>
</div>

<%= render 'list_entry' %>

app/views/url_entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @url_entry %>

<% if user_signed_in? && current_user.is_admin? %>
<div>
  <%= link_to "Back to url entries", root_path %> |
  <%= link_to "Edit this url entry", edit_url_entry_path(@url_entry) %> |
  <%= button_to "Destroy this url entry", @url_entry, method: :delete, :onclick => "return confirm('This will delete this link, are you sure?')" %>
</div>
<% end %>